{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ssh-proxy.serviceAccountName" . }}
  labels:
    {{- include "ssh-proxy.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-executor
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-executor
subjects:
- kind: ServiceAccount
  name: {{ include "ssh-proxy.serviceAccountName" . }}
roleRef:
  kind: Role
  name: pod-executor
  apiGroup: rbac.authorization.k8s.io
{{- end }}
