apiVersion: v1
kind: Service
metadata:
  name: {{ include "ssh-proxy.fullname" . }}
  labels:
    {{- include "ssh-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      targetPort: 22
      protocol: TCP
      name: ssh
  selector:
    {{- include "ssh-proxy.selectorLabels" . | nindent 4 }}
